# Release notes configuration
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - "skip-changelog"
    authors:
      - "dependabot"
      - "dependabot[bot]"
      - "renovate"
      - "renovate[bot]"
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
    - title: "New Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "bugfix"
        - "fix"
    - title: "Security"
      labels:
        - "security"
    - title: "Performance"
      labels:
        - "performance"
    - title: "Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "Other Changes"
      labels:
        - "*"
