[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "j2o"
version = "0.1.0"
description = "Jira to OpenProject migration tool"
authors = [
    {name = "SME", email = "sme@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.12,<4.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
j2o = "src.main:main"

[tool.setuptools]
packages = ["src"]
