# Jira to OpenProject Migration Configuration

# Jira API settings
jira:
  # Base URL of your Jira instance
  url: "https://jira.local/"
  # Authentication credentials
  username: ""  # Set via J2O_JIRA_USERNAME
  api_token: ""  # Set via J2O_JIRA_API_TOKEN
  # Projects to migrate (leave empty to migrate all)
  projects:
    - "PROJECT1"
    - "PROJECT2"
  # API request settings
  batch_size: 100
  # Fields to retrieve from Jira
  fields: "summary,description,issuetype,status,priority,assignee,reporter,created,updated,labels,components,fixVersions,versions,comment,attachment,worklog,customfield_*"
  # ScriptRunner integration
  scriptrunner:
    enabled: false  # Set via J2O_JIRA_SCRIPTRUNNER_ENABLED
    # Path relative to Jira URL (do not include https://jira.local/)
    custom_field_options_endpoint: "/rest/scriptrunner/latest/custom/getAllCustomFieldsWithOptions"  # Set via J2O_JIRA_SCRIPTRUNNER_CUSTOM_FIELD_OPTIONS_ENDPOINT

# OpenProject API settings
openproject:
  # Base URL of your OpenProject instance
  url: "https://openproject.local/"
  # Authentication credentials
  api_token: ""  # Set via J2O_OPENPROJECT_API_KEY
  # API request settings
  batch_size: 50

# Migration process settings
migration:
  # Component migration order
  component_order:
    - users
    - custom_fields
    - projects
    - versions
    - issues
    - relations
    - worklogs
    - attachments
    - comments

  # Data storage
  mapping_file: "data/id_mapping.json"
  attachment_path: "data/attachments"

  # User mapping staleness detection
  mapping:
    refresh_interval: "24h"  # TTL for user mapping cache entries
    fallback_strategy: "skip"  # Options: skip, assign_admin, create_placeholder
    fallback_admin_user_id: ""  # Admin user for assign_admin strategy (set via J2O_MAPPING_ADMIN_USER)

  # Performance settings
  batch_size: 1000

  # Behavior settings
  skip_existing: true

  # Security settings
  ssl_verify: true

  # Logging
  log_level: "INFO"
