# Development Environment Configuration
# This file contains development-specific overrides

# Development-specific settings
migration:
  log_level: "DEBUG"
  batch_size: 50  # Smaller batches for development

# Development database settings
database:
  postgres_db: "jira_migration_dev"
  postgres_user: "postgres"

# Development testing settings
test_mode: false
test_mock_mode: false
use_mock_apis: false 