# Staging Environment Configuration
# This file contains staging-specific overrides

# Staging-specific settings
migration:
  log_level: "INFO"
  batch_size: 100  # Medium batches for staging
  ssl_verify: true

# Staging database settings
database:
  postgres_db: "jira_migration_staging"
  postgres_user: "postgres"

# Staging testing settings
test_mode: false
test_mock_mode: false
use_mock_apis: false
